#pragma once

#include <vector>
#include <queue>
#include <random>
#include <atomic>
#include <thread>
#include <mutex>
#include <coroutine>
#include <string_view>

#include <async_mqtt/all.hpp>
#include <boost/asio.hpp>
#include <boost/format.hpp>

#include "source.h"

using mqtt_client_t = async_mqtt::client<async_mqtt::protocol_version::v5, async_mqtt::protocol::mqtt>;

class MQTTSource : public Source {
public:
    struct Metadata : IMetadata {
        std::string topic;
    };

    // Create with a descriptor and a buffer capacity
    static std::shared_ptr<MQTTSource> Create(ServiceBus& bus, const std::string& name, const Schema& schema, const Metadata& metadata, StorageManager& storage, boost::asio::io_context& ioc) {
        return std::make_shared<MQTTSource>(bus, name, schema, metadata, storage, ioc);
    }

    MQTTSource(ServiceBus& bus, const std::string& name, const Schema& schema, const Metadata& metadata, StorageManager& storage, boost::asio::io_context& ioc) :
        Source(bus, name, schema, storage, ioc), ioc_(ioc), cli_(ioc_.get_executor()),
        bus_(bus),
        topic_(metadata.topic) {
    }

    // Non-blocking attempt to acquire one sample buffer.
    bool DoTryAcquireSample(SampleHandle& outHandle, Instance& instance) override
    {
        return true;
    }
    // Blocking acquire with timeout: in this simple generator case we ignore timeout
    // and behave identical to TryAcquireSample (always returns immediately).
    bool DoAcquireSample(std::chrono::milliseconds /*timeout*/,
        SampleHandle& outHandle,
        const std::byte*& outData,
        size_t& outSize,
        Sample& outMeta) override
    {
        // For an on-demand random generator there's no waiting: just produce synchronously.
        return false;
    }

    // Release previously acquired buffer identified by handle.
    void DoReleaseSample(SampleHandle handle) override
    {
    }

protected:
    bool DoOnStart() override {
        host_ = "localhost";
        port_ = "1883";
        connect();
        return true;
    }

    void RunOnce() override {
    }

private:
    ServiceBus& bus_;

    void connect() {
        cli_.async_underlying_handshake(
            host_,
            port_,
            [this](auto&&... args) {
                handle_underlying_handshake(
                    std::forward<std::remove_reference_t<decltype(args)>>(args)...
                );
            }
        );
    }

    void reconnect() {
        tim_.expires_after(std::chrono::seconds{ 1 });
        tim_.async_wait(
            [this](async_mqtt::error_code const& ec) {
                if (!ec) {
                    connect();
                }
            }
        );
    }

    void handle_underlying_handshake(
        async_mqtt::error_code ec
    ) {
        bus_.Publish<Event>(Event{ Event::Type::Information, ec.message().c_str() });
        if (ec) {
            reconnect();
            return;
        }
        cli_.async_start(
            true,                // clean_start
            std::uint16_t(15),   // keep_alive
            "",                  // Client Identifier, empty means generated by the broker
            std::nullopt,        // will
            std::nullopt,
            std::nullopt,
            [this](auto&&... args) {
                handle_start_response(std::forward<decltype(args)>(args)...);
            }
        );
    }

    void handle_start_response(
        async_mqtt::error_code ec,
        std::optional<mqtt_client_t::connack_packet> connack_opt
    ) {
        bus_.Publish<Event>(Event{ Event::Type::Information, ec.message().c_str() });
        if (ec) {
            reconnect();
            return;
        }
        if (connack_opt) {
            std::cout << *connack_opt << std::endl;
        }

        // subscribe
        // MQTT send subscribe and wait suback
        std::vector<async_mqtt::topic_subopts> sub_entry{
            {topic_, async_mqtt::qos::at_most_once},
        };
        cli_.async_subscribe(
            *cli_.acquire_unique_packet_id(), // sync version only works thread safe context
            async_mqtt::force_move(sub_entry),
            [this](auto&&... args) {
                handle_subscribe_response(
                    std::forward<std::remove_reference_t<decltype(args)>>(args)...
                );
            }
        );
    }

    void handle_subscribe_response(
        async_mqtt::error_code ec,
        std::optional<mqtt_client_t::suback_packet> suback_opt
    ) {
        bus_.Publish<Event>(Event{ Event::Type::Information, ec.message().c_str() });
        if (ec) {
            reconnect();
            return;
        }
        cli_.async_recv(
            [this](auto&&... args) {
                handle_recv(
                    std::forward<std::remove_reference_t<decltype(args)>>(args)...
                );
            }
        );
    }

    void handle_recv(
        async_mqtt::error_code ec,
        std::optional<async_mqtt::packet_variant> pv_opt
    ) {
        bus_.Publish<Event>(Event{ Event::Type::Information, ec.message().c_str() });
        if (ec) {
            reconnect();
            return;
        }
        BOOST_ASSERT(pv_opt);
        if (pv_opt) {
            if (pv_opt.value().type() == async_mqtt::control_packet_type::publish) bus_.Publish<Event>(Event{ Event::Type::Information, "Publish packet received" });
            bus_.Publish<Event>(Event{ Event::Type::Information, std::to_string(pv_opt->size()).c_str() });
            async_mqtt::v5::publish_packet packet(pv_opt.value().get<async_mqtt::v5::publish_packet>());
            std::string payload = packet.payload();
            Instance instance(schema_.value());
            instance.set_data(payload.data());

            SubmitResult r = token_.try_submit(std::move(
                std::vector<std::byte>(reinterpret_cast<std::byte*>(
                    instance.get_data()),
                    reinterpret_cast<std::byte*>(instance.get_data()) + schema_.value().instance_size())
            ));
        }
        // next receive
        cli_.async_recv(
            [this](auto&&... args) {
                handle_recv(
                    std::forward<std::remove_reference_t<decltype(args)>>(args)...
                );
            }
        );
    }

    boost::asio::io_context& ioc_;
    std::string topic_;
    mqtt_client_t cli_;
    std::string host_;
    std::string port_;
    boost::asio::steady_timer tim_{ cli_.get_executor() };
};